/*
 * Created on November 29th 2023
 *
 * Copyright (C) 2023 Welltested AI - All Rights Reserved
 * The code in this file is Intellectutal Property of Welltested AI.
 * and can't be edited, redistributed or used without a valid license of it's product (Welltested)[https://welltested.ai]
 */

/// Welltested configuration class used for costumising the way the tests can be
/// generated using welltested. Currently supported costumizations:
/// - `generateMockFiles`: enable or disable the mock file generation automatically
/// after the tests has been generated
/// - `prefferedMockingLibrary`: ability to provide preffered 3rd party mocking
/// library that can be used to generate mocks. Currently supported options: none,
/// [mocktail](https://pub.dev/packages/mocktail), [mockito](https://pub.dev/packages/mockito)
abstract class WelltestedConfigurationFactory {

  bool _defaultGeneratedMockFiles = false;

  /// Parameter defines if Welltested should generated the mock files for the mock
  /// annotated class(if any). If set to `true`, welltested will generate mock files
  /// else mock files won't be generated by welltested automatically and user can
  /// generate them using `dart build runner` command. Default is `false`.
  bool get generateMockFiles => _defaultGeneratedMockFiles;

}
